//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone_Numbers
    {
        public int Phone_Number_Id { get; set; }
        public int Contact_Id { get; set; }
        public string Phone_Number { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual Contacts Contacts { get; set; }
    }
}
